### ISSUE TITLE
with withJoin 无法限制查询字段底层任然使用select* from

### ISSUE THREAD

**Issue by netmou** [top-think/framework#3045] opened 2024-08-22 03:06 UTC
### 所属功能组件

路由(Route)

### ThinkPHP 版本

8.0.3

### 操作系统

windows

### 错误信息

$data = EmailReceiver::field('read_time,title,email_id')->with('sender')->select();
$data = EmailReceiver::with('sender')->field('read_time,title')->select();
$data = EmailReceiver::withJoin(['sender'=>['sendto'=>'send','att_ids']])->select()->toArray();
$data = EmailReceiver::field('read_time,title,email_id')->withJoin(['sender'	=>	function($query) {
            $query->withfield(['sendto send', 'att_ids']);
}])->select()->toArray();;
以上几种想限制sender查询字段好像都不好使底层都是select *

**Comment by netmou** [comment] 2024-08-22 03:07
$data = EmailReceiver::with('sender')->field('read_time,title')->select();
又出现n+1问题sql执行了n遍

**Comment by netmou** [comment] 2024-08-22 03:08
文档没有提到如何限制主表字段，如何限制关联表字段，整体很混乱

**Comment by netmou** [comment] 2024-08-22 03:10
数据量很多的时候不限制字段怎么敢用模型关联

**Comment by liu21st** [comment] 2024-08-22 03:13
麻烦先仔细看手册 orm相关问题最好去orm库反馈

**Comment by big-dream** [comment] 2024-08-22 09:06
Duplicate of https://github.com/top-think/think-orm/issues/615

**Closed as not planned by big-dream** 2024-08-22 09:06 UTC
